### ISSUE TITLE
Comments on "Expose application and runtime metrics in Go using the expvar package"

### ISSUE THREAD

**Issue by Appeltabak** [OrangeTux/orangetux.nl#1]
Here are a few comments on your recent blogpost "Expose application and runtime metrics in Go using the expvar package":

>  I want to focus at the visits counter at the end of the JSON response.

`the JSON response` -> `this JSON response` -- reference slightly more clear I think

> The expvar.Map type can be used to make metrics appear under certain name space. 

`name space` -> namespace

Maybe noting that `memstats` from the previous given '/debug/vars' output is also an namespace (created with `expvar.Map`)

> This value must be recalculated every someone visits http://localhost:1818/debug/vars.

`every someone` -> `every time someone`

>  Together with a custom aggregrator, InfluxDB and Grafana I can monitor my applications very easy.

Not every reader will know about InfluxDB and Grafana, so maybe link those words to their websites.

PS A blogpost about nifty features you particularly like / use in Grafana would be a nice ;)

**Comment by OrangeTux** [comment]
Thanks for feedback. I used it to improve the post.
